from enum import Enum

class UserRole(str, Enum):
    FARMER = "FARMER"
    EXPERT = "EXPERT"
    ADMIN = "ADMIN"

class VerificationStatus(str, Enum):
    NOT_REQUIRED = "NOT_REQUIRED"
    PENDING = "PENDING"
    VERIFIED = "VERIFIED"
    REJECTED = "REJECTED"
    SUSPENDED = "SUSPENDED"

class AccountStatus(str, Enum):
    ACTIVE = "ACTIVE"
    SUSPENDED = "SUSPENDED"
    INACTIVE = "INACTIVE"

class ObservationStatus(str, Enum):
    SUBMITTED = "SUBMITTED"
    AI_ANALYZING = "AI_ANALYZING"
    AI_COMPLETED = "AI_COMPLETED"
    EXPERT_REVIEW_REQUIRED = "EXPERT_REVIEW_REQUIRED"
    PENDING_REVIEW = "PENDING_REVIEW" # compatible with EXPERT_REVIEW_REQUIRED
    UNDER_EXPERT_REVIEW = "UNDER_EXPERT_REVIEW"
    UNDER_REVIEW = "UNDER_REVIEW"     # compatible with UNDER_EXPERT_REVIEW
    MORE_INFORMATION_REQUIRED = "MORE_INFORMATION_REQUIRED"
    EXPERT_REVIEWED = "EXPERT_REVIEWED"
    REVIEWED = "REVIEWED"             # compatible with EXPERT_REVIEWED
    RESOLVED = "RESOLVED"
    COMPLETED = "COMPLETED"

class EscalationStatus(str, Enum):
    NOT_REQUIRED = "NOT_REQUIRED"
    RECOMMENDED = "RECOMMENDED"
    SUBMITTED = "SUBMITTED"
    UNDER_REVIEW = "UNDER_REVIEW"
    RESOLVED = "RESOLVED"
    NEEDS_MORE_INFORMATION = "NEEDS_MORE_INFORMATION"

class EscalationReason(str, Enum):
    LOW_CONFIDENCE = "LOW_CONFIDENCE"
    POOR_IMAGE_QUALITY = "POOR_IMAGE_QUALITY"
    MANUAL_FARMER_REQUEST = "MANUAL_FARMER_REQUEST"
    UNKNOWN_CLASS = "UNKNOWN_CLASS"
    HIGH_RISK_CONDITION = "HIGH_RISK_CONDITION"

class ReviewStatus(str, Enum):
    PENDING = "PENDING"
    IN_PROGRESS = "IN_PROGRESS"
    COMPLETED = "COMPLETED"
    NEEDS_INFO = "NEEDS_INFO"

class NotificationStatus(str, Enum):
    UNREAD = "UNREAD"
    READ = "READ"

class AuditAction(str, Enum):
    USER_REGISTER = "USER_REGISTER"
    USER_LOGIN = "USER_LOGIN"
    OBSERVATION_CREATED = "OBSERVATION_CREATED"
    IMAGE_UPLOADED = "IMAGE_UPLOADED"
    AI_ANALYSIS_PERFORMED = "AI_ANALYSIS_PERFORMED"
    CASE_ESCALATED = "CASE_ESCALATED"
    EXPERT_ASSIGNED = "EXPERT_ASSIGNED"
    EXPERT_REVIEW_SUBMITTED = "EXPERT_REVIEW_SUBMITTED"
    STATUS_CHANGED = "STATUS_CHANGED"
